//Cart
const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART';
const RESET_CART = 'RESET_CART';
const REORDER_CART = 'REORDER_CART';
//Map
const ADD_ADDRESS = 'ADD_ADDRESS';
const ADD_LOCATION = 'ADD_LOCATION';
const SELECT_ADDRESS = 'SELECT_ADDRESS';
//Setting
const CHANGE_MODE = 'CHANGE_MODE';

export {
  ADD_ITEM_TO_CART,
  INCREASE_QUANTITY,
  DECREASE_QUANTITY,
  DELETE_ITEM_FROM_CART,
  ADD_ADDRESS,
  ADD_LOCATION,
  SELECT_ADDRESS,
  RESET_CART,
  REORDER_CART,
  CHANGE_MODE,
};
